USING EXTERNAL FUNCTION compact_address(h3array ARRAY(VARCHAR))
RETURNS ARRAY(VARCHAR)
LAMBDA '<ARN>'
SELECT compact_address(h3cells) FROM (
USING EXTERNAL FUNCTION k_ring(origin VARCHAR, k INT) 
RETURNS ARRAY(VARCHAR) 
LAMBDA '<ARN>'
SELECT k_ring('8a3969ab2037fff', 10) AS h3cells)