USING EXTERNAL FUNCTION compact(h3array ARRAY(BIGINT))
RETURNS ARRAY(BIGINT)
LAMBDA '<ARN>'
SELECT compact(h3cells) FROM (
USING EXTERNAL FUNCTION k_ring(origin BIGINT, k INT) 
RETURNS ARRAY(BIGINT) 
LAMBDA '<ARN>'
SELECT k_ring(622506764662964223, 5) AS h3cells)