USING EXTERNAL FUNCTION h3_get_base_cell(h3 BIGINT) 
RETURNS INT 
LAMBDA '<ARN>'
SELECT h3_get_base_cell(h3) AS basecell FROM(
USING EXTERNAL FUNCTION geo_to_h3(lat DOUBLE, lng DOUBLE, res INT) 
RETURNS BIGINT 
LAMBDA '<ARN>'
SELECT geo_to_h3(43.552847, 7.017369, 10) AS h3)
-- 28